version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://sentinel:sentinel@postgres:5432/sentinel
      REDIS_URL: redis://redis:6379
      PORT: 4000
      NODE_ENV: development
      API_KEY_AGENT: agent-key
      API_KEY_LEAD: lead-key
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  pgdata:
